export const testimonyData = [
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Nitin_jangir.jpg',
		name: 'Amar Kumar',
		Branch: 'Computer Science',
		review: '“My experience at Sharda University is great and memorable. The mentors at Sharda University helped us enhance my academic and interpersonal skills. I am thankful to Training & Placement cell for providing a platform to enhance my skills and an opportunity to showcase them. In the last I am saying that The World is here at Sharda University."',
		placedIn: 'Microsoft',
	},
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Naveen_Bansal_.jpg',
		name: 'Naveen Bansal',
		review: '“It was a great experience studying at Sharda University, a memory to cherish for lifetime. My experience at Sharda was full of learning and grooming. Being a global university It gave me an opportunity to meet different kind of people from around the world and learnt many things from them. I am thankful to all the faculties, mentors and entire SET department for providing us with quality education. I am also grateful to TNP Cell for organising placements in this pandemic and helping me to get placed in 3 companies on Campus including Tcs Digital.   Overall it was a great experience and lifetime memory at Sharda University. If you want to make a career in CSE I would highly recommend you to join Sharda University.”',
		Branch: 'B.Tech. (CSE) ',
		placedIn: 'Google',
	},
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Tanveer_Mech.jpg',
		name: 'Tanveer Ahmad',
		Branch: 'B.Tech - Mechanical Engineering',
		review: '“It was my immense luck and fortune to be the part of Sharda University where I can grow. The entire faculty and department leaves no stone unturned to shape one\'s future. My four years at Sharda have been a wonderful experience of learning with prolific exposure to outside. Huge respect, love and devotion for entire faculty members and department. It\'s their efforts that make me to count myself into better professionals."',
		placedIn: 'Adobe',
	},
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Akash_Mech.jpg',
		name: 'Aakash Sharma',
		review: '“Sharda University has been a great contributor to the development of my personality. I have established my leadership, time management and team skills and have also been able to advance these skills to the whole new augment level. The infrastructure of Sharda University is one of the finest in the NCR region is what stands out the most. The best thing about this University is the cross-culture interaction between students from various parts of the world. The professors here make the university what it is today. With an attitude of being ever ready to help, and not only delivering classroom teachings, but they are also the pillars of the learning gained from this esteemed university and this is a treasure for life.”',
		Branch: 'B.Tech - Mechanical Engineering',
		placedIn: 'Google',
	},
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Md__Suyaib_CSE_IN.jpeg',
		name: 'Md Suyaib Ahmad',
		Branch: 'B.Tech - Computer Science',
		review: '“My four years at Sharda were great and a memory to cherish for lifetime. It was full of learning and grooming oneself. It gave me an opportunity to meet different kind of people and learned many things. I am thankful to all the faculties, mentors and entire SET as well as placement cell. Overall it was a great experience and lifetime memory at Sharda."',
		placedIn: 'Facebook',
	},
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Harsh_Pratap_CSE_IN.jpeg',
		name: 'Harsh Pratap Singh',
		review: '“Great experience from Sharda. You get a lot of opportunities. Work hard to get it. Be prepared for everything. Maintain your attendance.”',
		Branch: 'B.Tech. (CSE) ',
		placedIn: 'Samsung',
	},
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Sanchit_Bhatnagar_CSE_IN.jpeg',
		name: 'Amar Kumar',
		Branch: 'B.Tech - Computer Science',
		review: '“Great experience from Sharda. You get a lot of opportunities. Work hard to get it. Be prepared for everything. Maintain your attendance."',
		placedIn: 'Wipro Technologies',
	},
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Nitin_jangir.jpg',
		name: 'Amar Kumar',
		Branch: 'Computer Science',
		review: '“My experience at Sharda University is great and memorable. The mentors at Sharda University helped us enhance my academic and interpersonal skills. I am thankful to Training & Placement cell for providing a platform to enhance my skills and an opportunity to showcase them. In the last I am saying that The World is here at Sharda University."',
		placedIn: 'Microsoft',
	},
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Naveen_Bansal_.jpg',
		name: 'Naveen Bansal',
		review: '“It was a great experience studying at Sharda University, a memory to cherish for lifetime. My experience at Sharda was full of learning and grooming. Being a global university It gave me an opportunity to meet different kind of people from around the world and learnt many things from them. I am thankful to all the faculties, mentors and entire SET department for providing us with quality education. I am also grateful to TNP Cell for organising placements in this pandemic and helping me to get placed in 3 companies on Campus including Tcs Digital.   Overall it was a great experience and lifetime memory at Sharda University. If you want to make a career in CSE I would highly recommend you to join Sharda University.”',
		Branch: 'B.Tech. (CSE) ',
		placedIn: 'Google',
	},
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Tanveer_Mech.jpg',
		name: 'Tanveer Ahmad',
		Branch: 'B.Tech - Mechanical Engineering',
		review: '“It was my immense luck and fortune to be the part of Sharda University where I can grow. The entire faculty and department leaves no stone unturned to shape one\'s future. My four years at Sharda have been a wonderful experience of learning with prolific exposure to outside. Huge respect, love and devotion for entire faculty members and department. It\'s their efforts that make me to count myself into better professionals."',
		placedIn: 'Adobe',
	},
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Akash_Mech.jpg',
		name: 'Aakash Sharma',
		review: '“Sharda University has been a great contributor to the development of my personality. I have established my leadership, time management and team skills and have also been able to advance these skills to the whole new augment level. The infrastructure of Sharda University is one of the finest in the NCR region is what stands out the most. The best thing about this University is the cross-culture interaction between students from various parts of the world. The professors here make the university what it is today. With an attitude of being ever ready to help, and not only delivering classroom teachings, but they are also the pillars of the learning gained from this esteemed university and this is a treasure for life.”',
		Branch: 'B.Tech - Mechanical Engineering',
		placedIn: 'Google',
	},
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Md__Suyaib_CSE_IN.jpeg',
		name: 'Md Suyaib Ahmad',
		Branch: 'B.Tech - Computer Science',
		review: '“My four years at Sharda were great and a memory to cherish for lifetime. It was full of learning and grooming oneself. It gave me an opportunity to meet different kind of people and learned many things. I am thankful to all the faculties, mentors and entire SET as well as placement cell. Overall it was a great experience and lifetime memory at Sharda."',
		placedIn: 'Facebook',
	},
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Harsh_Pratap_CSE_IN.jpeg',
		name: 'Harsh Pratap Singh',
		review: '“Great experience from Sharda. You get a lot of opportunities. Work hard to get it. Be prepared for everything. Maintain your attendance.”',
		Branch: 'B.Tech. (CSE) ',
		placedIn: 'Samsung',
	},
	{
		img: 'https://www.sharda.ac.in/attachments/testimonial_images/thumbnail/Sanchit_Bhatnagar_CSE_IN.jpeg',
		name: 'Amar Kumar',
		Branch: 'B.Tech - Computer Science',
		review: '“Great experience from Sharda. You get a lot of opportunities. Work hard to get it. Be prepared for everything. Maintain your attendance."',
		placedIn: 'Wipro Technologies',
	},
	
	
]
